# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discription',
            field=models.TextField(default='discription default text '),
        ),
    ]
